### ISSUE TITLE
How to reproduce visualization results in README?

### ISSUE THREAD

**Issue by smileschang** [wjf5203/VNext#11]
Thanks for your wonderful work!

I'd like to reproduce the visualization results in your README.

I tried to add following 2 lines before [demo/demo.py#L29](https://github.com/wjf5203/VNext/blob/51c3e261b55407f78fcdc81aa73ca4493de2ba32/demo/demo.py#L29):
```
from detectron2.projects.idol import add_idol_config
    add_idol_config(cfg)
```
But it returrn this:
```
appuser@0916140fb4f2:~/VNext/demo$ python demo.py --config-file ../projects/IDOL/configs/ytvis19_swinL.yaml --video-input ../0b6db1c6fd.mp4 --output ../out --opts MODEL.WEIGHTS ../YTVIS19_SWINL_643AP.pth
[08/05 06:23:21 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='../projects/IDOL/configs/ytvis19_swinL.yaml', input=None, opts=['MODEL.WEIGHTS', '../YTVIS19_SWINL_643AP.pth'], output='../out', video_input='../0b6db1c6fd.mp4', webcam=False)
/home/appuser/.local/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[08/05 06:23:28 fvcore.common.checkpoint]: [Checkpointer] Loading from ../YTVIS19_SWINL_643AP.pth ...
[ERROR:0@10.023] global /io/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2927) open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:0@10.023] global /io/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (3002) open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
[ERROR:0@10.036] global /io/opencv/modules/videoio/src/cap.cpp (595) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.6.0) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /tmp/video_format_test3zylu0ek/test_file.mkv in function 'icvExtractPattern'


  0%|                                                                                    | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 178, in <module>
    for vis_frame in tqdm.tqdm(demo.run_on_video(video), total=num_frames):
  File "/home/appuser/.local/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "~/VNext/demo/predictor.py", line 129, in run_on_video
    yield process_predictions(frame, self.predictor(frame))
  File "~/VNext/detectron2/engine/defaults.py", line 317, in __call__
    predictions = self.model([inputs])[0]
  File "/home/appuser/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/VNext/projects/IDOL/idol/idol.py", line 249, in forward
    video_len = len(batched_inputs[0]['file_names'])
KeyError: 'file_names'
```

Could you give me some hint about how to pass right batched_inputs to forward function?

**Comment by QingZhong1996** [comment]
same error

**Comment by andreazuna89** [comment]
Same error. Please can you help us?

**Comment by andreazuna89** [comment]
I am using ytvis19_swinL.yaml  and YTVIS19_SWINL_643AP.pth as model weights. We can skip the 'file_names' error by removing ['file_names'] from this command: video_len = len(batched_inputs[0]['file_names']). But it remains a problem related to the predictions outputted by the model. It contains these keys: dict_keys(['image_size', 'pred_scores', 'pred_labels', 'pred_masks']) and not any of the detectron expected ones: "panoptic_seg", "instances" or "sem_seg" used for formatting qualitatively the output. Do we have to modify the detectron2 functions somehow for the IDOL configuration?

Thanks a lot

**Comment by aylinaydincs** [comment]
Did you find any solution for that?

**Comment by assia855** [comment]
I'm struggling with the some error:
`video_len = len(batched_inputs[0]['file_names'])
KeyError: 'file_names'
`
Did you find a solution please?

**Comment by andreazuna89** [comment]
Not yet solved. Can the authors help here?!

Thanks

**Comment by aylinaydincs** [comment]
If you did training, did you get AP results after evaluation in the log.txt file?!

I'm trying to get somewhere with this repository, but even though I manage the train the code, I couldn't see results and I couldn't able to test that results with demo either.

Please help!!

**Comment by unihornWwan** [comment]
> 

Hi, I have the same problem, have you solved it ?

**Comment by unihornWwan** [comment]
> https://github.com/wjf5203/VNext/issues/11#issuecomment-1348089140

Hi, I have the same problem, have you solved it ? thanks

**Comment by unihornWwan** [comment]
> I'm struggling with the some error: `video_len = len(batched_inputs[0]['file_names']) KeyError: 'file_names' ` Did you find a solution please?

Hi, I have the same problem, have you solved it ? thanks

**Comment by assia855** [comment]
@unihornWwan  sadly not yet.  @aylinaydincs  can you give us more detail on how you menage to train, which model , config file did you use and the parameters please. I'm struggling to launch the training.

**Comment by aylinaydincs** [comment]
> @unihornWwan sadly not yet. @aylinaydincs can you give us more detail on how you menage to train, which model , config file did you use and the parameters please. I'm struggling to launch the training.

I simply create a conda environmetn follow the [INSTALL.md](https://github.com/wjf5203/VNext/blob/main/INSTALL.md), after that I did what they say in [IDOL.md](https://github.com/wjf5203/VNext/blob/main/projects/IDOL/IDOL.md)

**Comment by assia855** [comment]
@unihornWwan  thanks for answering.

**Comment by Mamatharun** [comment]
@assia855 @unihornWwan I have the same issue to run the demo.py on a video. Have you solved it?

**Comment by netzahdzc** [comment]
@Mamatharun Hi, have you managed to run the demo.py on a video?

This is the error I'm trying to address: 
`OpenCV(4.7.0) /tmp/pip-install-vfgn61sf/opencv-python_0e92223a8fb94f898aa6f1cb2444dc3e/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /tmp/video_format_testu6cdg5yz/test_file.mkv in function 'icvExtractPattern'`

**Comment by reno77** [comment]
> @assia855 @unihornWwan I have the same issue to run the demo.py on a video. Have you solved it?

I've updated the demo_idol.py and predictor.py to visualize on videos. Currently I can draw the bounding boxes and the IDs. But not sure how to match the labels and confidence levels to IDs , since there are more labels and confidences returned than IDs.
My forked repo is over here https://github.com/reno77/VNext .
Cmd to infer on videos is : python projects/IDOL/demo_idol.py --config-file projects/IDOL/configs/ovis_swin.yaml --video-input input.mp4 --output output1.mp4

**Comment by babble2** [comment]
> > @assia855 @unihornWwan I have the same issue to run the demo.py on a video. Have you solved it?
> 
> I've updated the demo_idol.py from [lalalafloat](https://github.com/lalalafloat) to visualize on videos. I've set is_multi_cls to False to match the IDs to the pred_scores. My forked repo is over here https://github.com/reno77/VNext . Cmd to infer on videos is : python projects/IDOL/demo_idol.py --config-file projects/IDOL/configs/ovis_swin.yaml --video-input input.mp4 --output output1.mp4

你好，我直接推理可视化结果到了视频帧上，但目前还没不知道怎么得到mAP这些指标，可以一起交流下么，qq2211733735

**Comment by reno77** [comment]
> 

Hi, currently there's no mAP output since only a video is passed in. You'll need to provide the ground truth bounding boxes json file and implement your own function in demo_idol.py to read the file in and generate mAP by finding out the IOU between the ground truth and the inferred bboxes.

**Comment by reno77** [comment]
> > > @reno77 wan I have the same issue to run the demo.py on a video. Have you solved it?
> > 
> > 
> > I've updated the demo_idol.py from [lalalafloat](https://github.com/lalalafloat) to visualize on videos. I've set is_multi_cls to False to match the IDs to the pred_scores. My forked repo is over here https://github.com/reno77/VNext . Cmd to infer on videos is : python projects/IDOL/demo_idol.py --config-file projects/IDOL/configs/ovis_swin.yaml --video-input input.mp4 --output output1.mp4
> 
> 你好，我直接推理可视化结果到了视频帧上，但目前还没不知道怎么得到mAP这些指标，可以一起交流下么，qq2211733735

Hi, currently there's no mAP output since only a video is passed in. You'll need to provide the ground truth bounding boxes json file and implement your own function in demo_idol.py to read the file in and generate mAP by finding out the IOU between the ground truth and the inferred bboxes.
