### ISSUE TITLE
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

### ISSUE THREAD

**Issue by luoolu** [wjf5203/VNext#42]
> python3 projects/IDOL/train_net.py --config-file projects/IDOL/configs/ytvis19_swinL.yaml --num-gpus 2

Traceback (most recent call last):
  File "projects/IDOL/train_net.py", line 26, in <module>
    from detectron2.projects.idol import add_idol_config, build_detection_train_loader, build_detection_test_loader
  File "/home/user/PycharmProjects/VNext/projects/IDOL/idol/__init__.py", line 2, in <module>
    from .idol import IDOL
  File "/home/user/PycharmProjects/VNext/projects/IDOL/idol/idol.py", line 17, in <module>
    from .models.deformable_detr import DeformableDETR, SetCriterion
  File "/home/luolu/PycharmProjects/VNext/projects/IDOL/idol/models/deformable_detr.py", line 34, in <module>
    from .deformable_transformer import build_deforamble_transformer
  File "/home/luolu/PycharmProjects/VNext/projects/IDOL/idol/models/deformable_transformer.py", line 25, in <module>
    from .ops.modules import MSDeformAttn
  File "/home/luolu/PycharmProjects/VNext/projects/IDOL/idol/models/ops/modules/__init__.py", line 9, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/home/luolu/PycharmProjects/VNext/projects/IDOL/idol/models/ops/modules/ms_deform_attn.py", line 21, in <module>
    from ..functions import MSDeformAttnFunction
  File "/home/luolu/PycharmProjects/VNext/projects/IDOL/idol/models/ops/functions/__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/home/luolu/PycharmProjects/VNext/projects/IDOL/idol/models/ops/functions/ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

**Comment by babble2** [comment]
i meet same problems too, how do you solve it ?
